### PR TITLE
Add one more example, and Continuous Integration

### PR DESCRIPTION
**Pull request by armadillu**
Hey I've been adding CI to all the ofApp stuff, so I added it to ofxInterface too!
Also, Nicole has been learning ofxInteface so we've added the sketch she built to play with it as an example.

Hope it's all good! 
I see what you are doing with the JSON_UI, looks ambitious!

### CODE REVIEW

**Comment by galsasson** [comment]
Hi! Yes, ofxJsonUI is basically a mutant implementation of HTML and naturally I'm only building the things I need for projects so it will be very incomplete... :) But I'm just tired of writing the same things over and over again.

Oh man, hebrew is such a pain to render...

Is this PR include the previous one from Nicole?

**Comment by armadillu** [comment]
Looking forward to it! Not sure how you are doing the parsing if you are going the HTML way, but using pugi XML worked pretty well for me on ofxFontStash2...

Also, if you can afford offline rendering, using chrome to HTML render to texture (for the hebrew) might save u some time? although it would be nice to have something to render hebrew and other LTR languages for good.

And yeah this PR includes Nicole's example!

**Comment by galsasson** [comment]
Merged!
My concern about using chrome to render HTML is the alignment. Do you know if it can render a paragraph with no margins?

**Comment by armadillu** [comment]
Cool!

if you can do it in HTML (and I would think you can), then yes. Just imagine taking a screenshot of what chrome renders, that's what you get.
Take a look at this https://developers.google.com/web/updates/2017/04/headless-chrome

I think for what you need, you could just create a bunch of PNG's in a script (or with ofSystem()) at startup and keep them as cache. I couldn't get it to make transparent PNGs though, so you would need to craft your own pixels using CHrome's output as alpha channel. Might be a bit too much work to be worth it, but rendering right to left also sounds like a pain.

There's also this https://github.com/armadillu/ofxChrome But its not quite ready for prime time - it works but not 100% stable

**Comment by armadillu** [comment]
Also, glad you managed to find a job in the field :)

**Comment by galsasson** [comment]
Thanks, yeah I'm actually pretty busy already, not giving up to the high-tech industry yet!

I have something in place already to render out simple hebrew (a function that reverses the order of the letters). With multiline it is a bit more involved because I have to reverse the order of the letters but keep the order of the lines... pretty ugly indeed, but I think I'm good for now.

ofxChrome looks promising but for text rendering I still suspected alignment will be an issue. You need to specify the size of the window so there is no way to measure a paragraph or a line of text, right?

**Comment by armadillu** [comment]
yep you are right - you won't be able to get bounds size easily b4 you render
In theory I could retrieve your <div> size (I can run javascript) and then resize the window to that size and then render out, but its gets complicated

**Comment by galsasson** [comment]
right, the javascript option sounds possible, might be worth a shot for complex text rendering.

**Pull request merged**
